name       : librist
version    : 0.2.7
release    : 1
source     :
    - https://code.videolan.org/rist/librist/-/archive/v0.2.7/librist-v0.2.7.tar.gz : 7e2507fdef7b57c87b461d0f2515771b70699a02c8675b51785a73400b3c53a1
license    : BSD-2-Clause
homepage   : https://code.videolan.org/rist/librist
component  : multimedia.library
summary    : A library that can be used to easily add the RIST protocol to your application
description: |
    A library that can be used to easily add the Reliable Internet Stream Transport (RIST) protocol to your application, written to comply with the Video Services Forum (VSF) Technical Recommendations TR-06-1 and TR-06-2.
builddeps  :
    - mbedtls-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
